---
title: "Raspagem de dados com o Python e Estatística com o R: Um estudo dos equipamentos culturais no estado do Rio de Janeiro"
author: "Lyncoln  & Steven"
date: "16 de março de 2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introdução

Até a sua extinção o Ministério da cultura afirmava que seus resultados mostravam as grandes diversidades artísticas e culturais existentes nos municípios. Todavia, falava muito pouco sobre os equipamentos culturais.

O Brasil não tem um quadro de informações sobre a cultura disponível para qualquer cidadão. O que temos são tentativas de atender a demanda com informações a partir de pesquisas pontuais. Dentre as pesquisas cumpre registrar o papel do IBGE com diversas pesquisas como o Sistema de Indicadores Culturais (2003, 2005) e o perfil de informações básicas municipais – Cultura  (Munic Cultura, 2006). Essas pesquisas, que não são contínuas, são a melhores fontes de informações sobre equipamentos culturais. 

Nesse sentido, o que se pretende com esse trabalho é explorar as informações oficiais sobre os equipamentos culturais. Buscamos criar um mecanismo contínuo de informações sobre os equipamentos culturais do estado do Rio de Janeiro: o Mapa da Cultura.

A construção desse mapa será util para responder alguns questionamentos:

1.Existe uma assimetria na distribuição de equipamentos culturais no estado?  
2.Se existir, essa assimetria leva a desigualdade na distribuição dos equipamentos culturais do Estado?  
3. Como deixar disponível as informações geolocalizadas contidas na secretaria Estado do Rio de Janeiro?

A partir das informações disponíveis na secretaria de Cultura do Estado do Rio de Janeiro, buscaremos raspar dados com o Python e gerar visualizações de dados com o R para a ánalise desses questionamento.

Este trabalho está dividido em 04 etapas. A seguir está uma análise da gestão dos equipamentos culturais. Em seguida, será detalhada as etapas para a raspagem de dados utilizando o Python. Após ess etapa, vamos mostrar o procedimento para a geração do mapa da cultura utilizando o R. Seguido por uma análise da concentração e da desigualdade dos equipamentos culturais. Finalmente, vamos apontar alguns indicadores de desigualdade espacial no que tange a distribuição dos equipamentos no estado do Rio de Janeiro.

## Ausência de Gestão Cultural

De acordo com Barros & Ziviani (2009), a área da Cultura sofre com uma baixa institucionalização e despreparo dos municípios quanto a importância das informações das políticas voltadas para o setor. Sem dados torna-se impossível a alocação de equipamentos culturais de forma eficiente e justa. Dados sobre a cultura são fundamentais para uma boa politica cultural. Todavia, no Brasil, existem muito poucas informações sobre a gestão cultural. isso se deve, em grande parte, ao jeito informal que o setor da cultura representa no Estado Brasileiro. Assim, “em sua maioria, a gestão da cultura encontra-se acoplada a outro setor, como o turismo, a educação e até mesmo a saúde, como já ocorreu em tempos passados na instancia federal” (Barros & Ziviani, 2009).

“Nesse sentido, em sua maioria, o conceito está associado a noção de direitos culturais como parte dos direitos humanos sendo a dimensão cultural indispensável e, acima de tudo, estratégica para qualquer projeto de desenvolvimento. Por conseguinte, o reconhecimento e a valorização da diversidade cultural estão ligados à democracia cultural, democratização da gestão cultural, participação da sociedade civil nas decisões políticas e no processo de Gestão Pública descentralização da produção entre outros aspectos (Barros & Ziviani, 2009).

## Método

Para realizar essa pesquisa, foi necessário raspar informações de espaços culturais presentes no Estado do Rio de Janeiro através do site mapadecultura.rj.gov.br. Foi utilizado a linguagem de programação python com as bíbliotecas scrapy e re para o processo de raspagem e o R com as bíbliotecas tidyverse, leaflet, ggmap, readxl, leaflet.extras e rgdal.


#### Material com o Python

Foi criado uma "spider" utlizando o pacote scrapy do python que "rasteja" pelo site do mapadecultura na aba espaços culturais. O processo começa com o link da primeira aba da categoria espaços culturais e com isso o python irá guardar o link de todas os posts de espaços culturais presentes na aba. Com os links de cada post, o código irá para o site do post e em seguida irá salvar em uma variável o código html de todo o corpo de texto, e utilizando o pacote re, irá filtrar o endereço, em seguida irá extrair o nome do lugar e salvar em um documento txt no formato "titulo";"endereço".Com toda os posts da primeira aba extraídos, o código irá analisar se existe um link para próxima aba, se existir, o processo irá se repetir para aquela aba.
Com todos as informações que precisamos extraídas, iremos utilizar o documento txt gerado para trabalharmos na linguagem R.






#### Visualização de dados com o R

Com o arquivo txt gerado anteriormente, foi preciso um pequeno tratamento manual pois algumas poucas vezes houve erro de enconding por falta de padrão presente no site do mapacultural que apresentava problemas para o R. Também observamos que quando há uma rede de lugares, por exemplo cinemas, o site agrupava os endereços em um só post, então tivemos que separar esses lugares de modo que cada um possua seu próprio nome e endereço.

Foi utilizado o pacote readxl para que importassemos o arquivo txt para o R em formato de um tibble e em seguida foi criado colunas chamadas de "latitude" e "longitude" preenchidas todas com 999 para que depois possemos preenchelas com os dados geográficos de cada endereço do tibble.

Por falta de padrão de endereços no site, foi criado um processo utilizando o pacote stringR em que cada endereço será analisado e se não houver contido a palavra "RJ" ou "Rio de Janeiro" em alguma parte, o código irá concatenar "Rio de Janeiro" no final.

Foi preciso adquirir uma API do google que nos permitisse acessar dados do google map, foi necessário realizar cadastro na plataforma google cloud e configurar a API para que fosse possível utilizar o R para obter dados de latitude e longitude.

Com o pacote ggmap, cadastramos a chave da API para assim utilizarmos a função geocode para que ela retorne a latitude e longitude de cada endereço disponível no tibble. Alguns poucos lugares apresentaram erro na sua geolocalização por causa de possíveis erros de endereço no site ou até mesmo por estarem incompletos. Foi feito uma rápida pesquisa para que esses problemas fossem resolvidos e assim criamos um processo em que utlizamos a função geocode em cada endereço do tibble anteriormente criado e salvasse sua latitude e longitude nas devidas colunas. Assim obtivemos um tibble com nome, endereço, latitude e longitude de todos os espaços culturais presentes no site mapadecultura.rj.gov.br .







## O Mapa da Cultura


## Resultados do Mapa da Cultura


## Conclusão

## Referências

BARROS, José Márcio & ZIVIANI, Paula Equipamentos, meios e atividades culturais nos municípios brasileiros: indicadores de diferenças, desigualdades e diversidade cultural IN:  CALABRE, Lia Políticas culturais : reflexões e ações. São Paulo : Itaú Cultural ; Rio de Janeiro : Fundação Casa de Rui Barbosa, 2009.  
IBGE.  Sistema  de  informações  e  indicadores  culturais  2003-2005.  v.  22.  Rio  de Janeiro: IBGE, 2007. 129 p.
_____. Pesquisa dos municípios brasileiros – Cultura 2006. Rio de Janeiro: IBGE, 2007. 268 p.
_____. Sistema de informações e indicadores culturais 2003. V. 18. Rio de Janeiro: IBGE, 2006. 126 p.